version: '3.1'

services:
  app:
    build: .
    restart: always
    depends_on:
      - postgres
    ports:
      - "5005:5005"
    environment:
      - SQALCHMY_DATABASE_URI=${DATABASE_URI}
      - SECRET_KEY=${SECRET_KEY}
  postgres:
    image: postgres:12
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}