"""empty message

Revision ID: 06338787afa0
Revises: c0eac81421ab
Create Date: 2021-11-07 20:20:17.073878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06338787afa0'
down_revision = 'c0eac81421ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['login'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
